name: front-guard-dev

services:

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - ./.env/.env.dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mock_api:
    build:
      context: ./mock-radar
    environment:
      - FLASK_ENV=dev
    ports:
      - "5000:5000"



# Add yarn install to dev build of frontend/backend to sync any dependancy changes

# Use secrets instead of environment variables

# command: sh -c "yarn install && cp yarn.lock /app && yarn start"