name: front-guard-dev

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # develop:
    #   watch: 
    #     - path: ./frontend/src
    #       action: rebuild
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # develop:
    #   watch: 
    #     - path: ./backend/src
    #       action: rebuild
    env_file:
      - ./.env/.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./db
      target: dev
    env_file:
      - ./.env/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# Add yarn install to dev build of frontend/backend to sync any dependancy changes

# Use secrets instead of environment variables

# Need radar service

# command: sh -c "yarn install && cp yarn.lock /app && yarn start"