name: front-guard-dev

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env/.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./db
      target: dev
    env_file:
      - ./.env/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# Use secrets instead of environment variables

# Need radar service

# build:
#   context: ./frontend
#   target: prod


# Mount db init script during dev, bake for prod