name: front-guard

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./frontend/build:/usr/share/nginx/html
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    #   - DATABASE_URL=postgres://user:password@db:5432/mydb
  db:
    image: postgres:16.4-alpine3.20
    # env_file:
    #   - ./db/.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=mydb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sql

# docker exec -it front-guard-db-1 psql -U myuser -d mydb

# Need dev/prod profiles
# Need radar service

# build:
#   context: ./frontend
#   target: prod

# Consider a multi stage build for react -> nginx

# Mount db init script during dev, bake for prod