name: front-guard-prod

# docker compose -f production.yml up -d --build

services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./.env/.env.prod
    depends_on:
      - db
    restart: unless-stopped
  db:
    build:
      context: ./db
      target: prod
    env_file:
      - ./.env/.env.prod
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
  mock_api: # Should also use nginx but would require another container
            # But shouldn't bother as it should nearly be in its own repository
            # Could possibly host through the frontends nginx server though
    build:
      context: ./mock-radar
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=prod
    restart: unless-stopped