name: front-guard-prod

# docker compose -f production.yml build
# docker compose -f production.yml up -d

services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./.env/.env.prod
    depends_on:
      - db
  db:
    build:
      context: ./db
      target: prod
    env_file:
      - ./.env/.env.prod
    volumes:
      - ./db/data:/var/lib/postgresql/data