FROM mathworks/matlab:r2023a

# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /app/requirements.txt

# RUN pip3 install --no-cache-dir -r /app/requirements.txt

# WORKDIR /app

# COPY . /app

## Copy your script/function to be executed.
# COPY myscript.m ./

## Start MATLAB in batch mode and execute your script/function.
# CMD ["matlab","-batch","myscript"]